<?php
/**
 * @package SP Page Builder
 * @author JoomShaper http://www.joomshaper.com
 * @copyright Copyright (c) 2010 - 2022 JoomShaper
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 or later
*/

use Joomla\CMS\Language\Text;

//no direct accees
defined ('_JEXEC') or die ('restricted aceess');

// Common
Text::script('COM_SPPAGEBUILDER_FRONTEND_EDITOR');
Text::script('COM_SPPAGEBUILDER_PREVIEW');
Text::script('COM_SPPAGEBUILDER_APPLY');
Text::script('COM_SPPAGEBUILDER_CANCEL');

// Media Manager
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_UPLOAD_FILES');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_CLOSE');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_INSERT');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_SEARCH');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_CANCEL');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_DELETE');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_CONFIRM_DELETE');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_LOAD_MORE');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_UNSUPPORTED_FORMAT');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_BROWSE_MEDIA');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_BROWSE_FOLDERS');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_CREATE_FOLDER');
Text::script('COM_SPPAGEBUILDER_ADDON_ICON_SELECT');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_ENTER_DIRECTORY_NAME');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_MEDIA_UPLOADING');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_UPLOAD_FAILED');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_MEDIA_LARGE');
Text::script('COM_SPPAGEBUILDER_MEDIA_MANAGER_FILE_NOT_SUPPORTED');

// Row
Text::script('COM_SPPAGEBUILDER_ROW_OPTIONS');
Text::script('COM_SPPAGEBUILDER_ADD_NEW_ROW');
Text::script('COM_SPPAGEBUILDER_DUPLICATE_ROW');
Text::script('COM_SPPAGEBUILDER_DISABLE_ROW');
Text::script('COM_SPPAGEBUILDER_ENABLE_ROW');
Text::script('COM_SPPAGEBUILDER_COPY_ROW');
Text::script('COM_SPPAGEBUILDER_ROW_COPIED');
Text::script('COM_SPPAGEBUILDER_PASTE_ROW');
Text::script('COM_SPPAGEBUILDER_DELETE_ROW');
Text::script('COM_SPPAGEBUILDER_ROW_TOGGLE');
Text::script('COM_SPPAGEBUILDER_DELETE_ROW_CONFIRMATION');
Text::script('COM_SPPAGEBUILDER_ROW_COLUMNS_MANAGEMENT');
Text::script('COM_SPPAGEBUILDER_GLOBAL_CUSTOM');
Text::script('COM_SPPAGEBUILDER_ROW_COLUMNS_CUSTOM');
Text::script('COM_SPPAGEBUILDER_ROW_COLUMNS_GENERATE');
Text::script('COM_SPPAGEBUILDER_IMPORT_PAGE');
Text::script('COM_SPPAGEBUILDER_IMPORT_PAGE_ALT');
Text::script('COM_SPPAGEBUILDER_EXPORT_PAGE');
Text::script('COM_SPPAGEBUILDER_PAGE_TEMPLATES');
Text::script('COM_SPPAGEBUILDER_UNDO');
Text::script('COM_SPPAGEBUILDER_REDO');
Text::script('COM_SPPAGEBUILDER_SAVE');
Text::script('COM_SPPAGEBUILDER_SAVE_ROW');

//Addon
Text::script('COM_SPPAGEBUILDER_ROW_COLUMNS_OPTIONS');
Text::script('COM_SPPAGEBUILDER_DELETE_COLUMN');
Text::script('COM_SPPAGEBUILDER_ADD_NEW_ADDON');
Text::script('COM_SPPAGEBUILDER_ADDON');
Text::script('COM_SPPAGEBUILDER_DELETE_ADDON');
Text::script('COM_SPPAGEBUILDER_DUPLICATE_ADDON');
Text::script('COM_SPPAGEBUILDER_EDIT_ADDON');
Text::script('COM_SPPAGEBUILDER_ADDONS_LIST');
Text::script('COM_SPPAGEBUILDER_ALL');
Text::script('COM_SPPAGEBUILDER_MODAL_CLOSE');
Text::script('COM_SPPAGEBUILDER_DISABLE_COLUMN');
Text::script('COM_SPPAGEBUILDER_ENABLE_COLUMN');

Text::script('COM_SPPAGEBUILDER_YES');
Text::script('COM_SPPAGEBUILDER_NO');
Text::script('COM_SPPAGEBUILDER_PAGE_TEMPLATES_LIST');
Text::script('COM_SPPAGEBUILDER_PAGE_TEMPLATE_LOAD');
Text::script('COM_SPPAGEBUILDER_ENABLE_ADDON');
Text::script('COM_SPPAGEBUILDER_DISABLE_ADDON');
Text::script('COM_SPPAGEBUILDER_ADDON_PARENT_COLUMN');
Text::script('COM_SPPAGEBUILDER_ADD_NEW_INNER_ROW');
Text::script('COM_SPPAGEBUILDER_MOVE_COLUMN');

Text::script('COM_SPPAGEBUILDER_DAY');
Text::script('COM_SPPAGEBUILDER_DAYS');
Text::script('COM_SPPAGEBUILDER_HOUR');
Text::script('COM_SPPAGEBUILDER_HOURS');
Text::script('COM_SPPAGEBUILDER_MINUTE');
Text::script('COM_SPPAGEBUILDER_MINUTES');
Text::script('COM_SPPAGEBUILDER_SECOND');
Text::script('COM_SPPAGEBUILDER_SECONDS');

Text::script('COM_SPPAGEBUILDER_ADDON_OPTIN_FORM_SUBCSCRIBE');
Text::script('COM_SPPAGEBUILDER_ADDON_AJAX_CONTACT_NAME');
Text::script('COM_SPPAGEBUILDER_ADDON_AJAX_CONTACT_EMAIL');
Text::script('COM_SPPAGEBUILDER_SAVE_ADDON');
